version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: webchat_db
      POSTGRES_USER: webchat_user
      POSTGRES_PASSWORD: webchat_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webchat_user -d webchat_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://webchat_user:webchat_password@db:5432/webchat_db
      - DEBUG=True
      - SECRET_KEY=your-secret-key-change-this-in-production
    volumes:
      - ./static/uploads:/app/static/uploads
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data:
