"""Add reactions table

Revision ID: 294520e83915
Revises: 8f5c25e599f2
Create Date: 2025-06-26 17:38:32.066808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294520e83915'
down_revision = '8f5c25e599f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
