"""Add user preferences table

Revision ID: cba0dfcc803e
Revises: 294520e83915
Create Date: 2025-06-26 17:54:10.089726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba0dfcc803e'
down_revision = '294520e83915'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
